// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwueqkusxarhomnabcrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dWVxa3VzeGFyaG9tbmFiY3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTg1NDksImV4cCI6MjA2Mzc5NDU0OX0.SSNIKLPlKnS_PR74dvCk_EksYNnYh4q-K7lXGrA9uIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);